services:
  tarantool:
    image: tarantool/tarantool:3.6
    container_name: tarantool
    restart: unless-stopped
    ports:
      - "3301:3301"
    volumes:
      - ./tarantool:/opt/tarantool
      - ./data:/var/lib/tarantool
    working_dir: /opt/tarantool
    environment:
      TARANTOOL_LOG: /dev/stdout
      TARANTOOL_LOG_LEVEL: 5
      TARANTOOL_USER: ${TARANTOOL_USER}
      TARANTOOL_PASSWORD: ${TARANTOOL_PASSWORD}
    entrypoint: ["tarantool"]
    command: ["--name", "instance-001", "--config", "/opt/tarantool/config.yaml"]
    healthcheck:
      test: ["CMD-SHELL", "bash -lc 'cat < /dev/null > /dev/tcp/127.0.0.1/3301'"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"$${REDIS_PASSWORD}\" ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  auth:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    image: auth
    container_name: auth
    restart: unless-stopped
    depends_on:
      - tarantool
      - redis
    ports:
      - "8081:8081"
      - "9090:9090"
    environment:
      AUTH_HTTP_ADDRESS: ":8081"
      AUTH_GRPC_ADDRESS: ":9090"
      TARANTOOL_ADDR: "tarantool:3301"
      TARANTOOL_USER: ${TARANTOOL_USER}
      TARANTOOL_PASSWORD: ${TARANTOOL_PASSWORD}
      REDIS_ADDR: "redis:6379"
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TTL_MIN: ${JWT_ACCESS_TTL_MIN}
      JWT_REFRESH_TTL_DAYS: ${JWT_REFRESH_TTL_DAYS}
    volumes:
      - ./public:/app/public

volumes:
  tarantool_data:

