local M = {
    PHONE_ALREADY_EXISTS = "PHONE_ALREADY_EXISTS",
    ROLE_NOT_FOUND = "ROLE_NOT_FOUND",
    ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND",
    USER_NOT_FOUND = "USER_NOT_FOUND",
    ALREADY_ACTIVE = "ALREADY_ACTIVE",
}

return M