local E = {
    PHONE_ALREADY_EXISTS = "PHONE_ALREADY_EXISTS",
    ROLE_NOT_FOUND = "ROLE_NOT_FOUND",
    ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND",
    USER_NOT_FOUND = "USER_NOT_FOUND",
    ALREADY_ACTIVE = "ALREADY_ACTIVE",
    ALREADY_NOT_ACTIVE = "ALREADY_NOT_ACTIVE",
    USER_SET_PASSWORD = "USER_SET_PASSWORD",

    NAME_IS_NULL = "NAME_IS_NULL",
    SLUG_IS_NULL = "SLUG_IS_NULL",
    NAME_ALREADY_EXISTS = "NAME_ALREADY_EXISTS",
    SLUG_ALREADY_EXISTS = "SLUG_ALREADY_EXISTS",
}

return E